webapp/models.py
# models.py
from webapp.mydb import get_db

def get_db_connection():
    return get_db()

def get_products_ending_with_a():
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)
    query = """SELECT * FROM image INNER JOIN product
ON product.product_ID = image.product_ID
WHERE image.image_name LIKE '%(1)%';"""
    cursor.execute(query)
    products = cursor.fetchall()
    cursor.close()
    connection.close()
    return products

def get_product_by_id(product_id):
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)
    query = """
    SELECT p.*, GROUP_CONCAT(i.image_name) as images
    FROM product p
    LEFT JOIN image i ON p.product_ID = i.product_ID
    WHERE p.product_ID = %s AND i.image_active = 'yes'
    GROUP BY p.product_ID;
    """
    cursor.execute(query, (product_id,))
    product = cursor.fetchone()
    cursor.close()
    connection.close()
    if product and 'images' in product:
        product['images'] = product['images'].split(',')
    return product

def get_all_products():
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)
    query = """SELECT * FROM product;"""
    cursor.execute(query)
    product = cursor.fetchall()
    cursor.close()
    connection.close()
    return product

webapp/__init__.py
# __init__.py
from flask import Flask
from .config import DB_CONFIG

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'dlskfjlkos sodijflsaiuro'
    app.config['DATABASE_CONFIG'] = DB_CONFIG

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    return app

webapp/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, session,flash
from webapp.mydb import get_db
import hashlib
from datetime import datetime
from .decorators import admin_required
import mysql.connector
auth= Blueprint('auth', __name__)




@auth.route('/show_product')
def show_product():
    return render_template("show_product.html")  

@auth.route('/indexAdmin')
def indexAdmin():
    return render_template("indexAdmin.html")  



auth = Blueprint('auth', __name__)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        customer_name = request.form['customer_name_and_last_name']
        customer_number = request.form['customer_number']
        customer_email = request.form['email']
        customer_password = request.form['password']
        customer_password2 = request.form['customer_password2']

        if customer_password != customer_password2:
            return redirect(url_for('auth.signup', msg='invalidPassword'))

        try:
            cnx = get_db()
            cursor = cnx.cursor()

            passwordHash = hashlib.sha256(customer_password.encode()).hexdigest()

            insert_query = """
            INSERT INTO customer (customer_name_and_last_name,customer_number , email, password, customer_date)
            VALUES (%s, %s, %s, %s, %s)
            """
            data = (customer_name, customer_number, customer_email, passwordHash, datetime.now())
            cursor.execute(insert_query, data)
            cnx.commit()

            cursor.close()
            cnx.close()

            session['email'] = customer_email
            return redirect(url_for('views.index'))
        except mysql.connector.Error as err:
            print(err)
            return redirect(url_for('auth.signup', msg='error'))
    
    return render_template('signup.html')

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    if request.method == 'POST':
        customer_email = request.form['email']
        customer_password = request.form['password']

        try:
            cnx = get_db()
            cursor = cnx.cursor()

            passwordHash = hashlib.sha256(customer_password.encode()).hexdigest()

            query = """
            SELECT * FROM customer WHERE email=%s AND password=%s
            """
            cursor.execute(query, (customer_email, passwordHash))
            result = cursor.fetchone()

            if result:
                session['email'] = customer_email
                return redirect(url_for('views.index'))
            else:
                return redirect(url_for('auth.signin', msg='invalid'))
        except mysql.connector.Error as err:
            print(err)
            return redirect(url_for('auth.signin', msg='error'))

    return render_template('signin.html')


@auth.route('/indexAdmin')
@admin_required
def indexAdmin():
    return render_template("indexAdmin.html")

webapp/views.py
# views.py
from flask import Blueprint, render_template,session
from .models import get_products_ending_with_a, get_product_by_id,get_all_products

views = Blueprint('views', __name__)

@views.route('/')
def index():
    products = get_products_ending_with_a()
    email = session.get('email')
    return render_template("index.html", products=products,email=email)


@views.route('/product/<int:product_id>')
def show_product(product_id):
    product = get_product_by_id(product_id)
    return render_template("show_product.html",product=product)


@views.route('/show_all_products')
def show_all_products():
    product = get_all_products()
    return render_template('a_p_show_all_products.html', product=product)

webapp/templates/a_p_show_all_products.html
{% extends "base_user.html" %}

{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">همه سفارشات این ماه</h6>
            <a href="">نمایش همه</a>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-white">
                        <th scope="col">ویرایش <i class="fas fa-pen-fancy"></i></th>
                        <th scope="col">اسم محصول</th>
                        <th scope="col">دسته بندی</th>
                        <th scope="col">قیمت محصول</th>
                        <th scope="col">سایز محصول</th>
                        <th scope="col">صفت محصول</th>
                        <th scope="col">مارک محصول</th>
                        <th scope="col">عکس محصول</th>
                        <th scope="col">سود محصول</th>
                        <th scope="col">فعالیت</th>
                        <th scope="col">ID</th>
                        <th scope="col">افزودن <i class="fas fa-pen-fancy"></i></th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in product %}
                    <tr>
                        <th><a href="">ویرایش <i class="fas fa-pen-fancy"></i></a></th>
                        <td>{{ product['product_name'] }}</td>
                        <td>{{ product['category_ID'] }}</td>
                        <td>{{ product['product_port'] }}</td>
                        <td>{{ product['product_explan'] }}</td>
                        <td>{{ product['product_mark'] }}</td>
                        <td>{{ product['product_active'] }}</td>
                        <td>{{ product['product_ID'] }}</td>
                        <th><a href="">افزودن <i class="fas fa-pen-fancy"></i></a></th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>


<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<title>{% block title %}SmartStor Template{% endblock %}</title>

<!-- Bootstrap -->
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />

<!-- Slick -->
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/slick.css') }}" />
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/slick-theme.css') }}" />

<!-- nouislider -->
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/nouislider.min.css') }}" />

<!-- Font Awesome Icon -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">

<!-- Custom stlylesheet -->
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

</head>
<body>
	<!-- HEADER -->
	<header>
		<!-- TOP HEADER -->
		<div id="top-header">
			<div class="container">
				<ul class="header-links pull-left">
					<li><a href="#"><i class="fa fa-phone"></i> +98936902400</a></li>
					<li><a href="#"><i class="fa fa-envelope-o"></i>
							smartcar@email.com</a></li>
					<li><a href="#location"><i class="fa fa-map-marker"></i>موقعیت
							تهران</a></li>
				</ul>
				<ul class="header-links pull-right">
							{% if email is not none %}
							<li><a href=""><i class="fa fa-user-o"></i>پروفایل شما</a></li>
							{% set email = email %}
							<li><a href=""> {{ email }} :ایمیل شما</a></li>
						{% else %}
						<li><a href="">هیچ ایمیلی وارد نشده است</a></li>
						<li><a href=""><i class="fa fa-user-o"></i>وارد ایمیل خود شوید</a></li>
						{% endif %}
				</ul>
			</div>
		</div>
		<!-- /TOP HEADER -->

		<!-- MAIN HEADER -->
		<div id="header">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- LOGO -->
					<div class="col-md-3">
						<div class="header-logo">
							<a href="#" class="logo"> <img src="{{ url_for('static', filename='./img/logo.jpg') }}" alt="">
							</a>
						</div>
					</div>
					<!-- /LOGO -->

					<!-- SEARCH BAR -->
					<div class="col-md-6">
						<div class="header-search">
							<form>
								<select class="input-select">
									<option value="0"><a href="/">همه محصولات</a></option>
									<option value="1"><a href="storeTV.html">فیلتر</a></option>
									<option value="2"><a href="storemachin.html">شمع</a></option>

								</select> <input class="input" placeholder="Search here">
								<button class="search-btn">Search</button>
							</form>
						</div>
					</div>
					<!-- /SEARCH BAR -->

					<!-- ACCOUNT -->
					<div class="col-md-3 clearfix">
						<div class="header-ctn">
							<!-- Wishlist -->
							<div>
								<a href="#"> <i class="fa fa-heart-o"></i> <span>Your
										Wishlist</span>
									<div class="qty">2</div>
								</a>
							</div>
							<!-- /Wishlist -->


							<!-- Cart -->
							<div class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown"
									aria-expanded="true"> <i class="fa fa-shopping-cart"></i> <span>Your
										Cart</span>
									<div class="qty">3</div>
								</a>
								<div class="cart-dropdown">
									<div class="cart-list">
										<div class="product-widget">
											<div class="product-img">
												<img src="./img/product6.jpg" alt="">
											</div>
											<div class="product-body">
												<h3 class="product-name">
													<a href="#">لباسشویی</a>
												</h3>
												<h4 class="product-price">
													<span class="qty">1x</span>ریال 16000
												</h4>
											</div>
											<button class="delete">
												<i class="fa fa-close"></i>
											</button>
										</div>

										<div class="product-widget">
											<div class="product-img">
												<img src="./img/product6.jpg" alt="">
											</div>
											<div class="product-body">
												<h3 class="product-name">
													<a href="#">تلویزیون</a>
												</h3>
												<h4 class="product-price">
													<span class="qty">3x</span>ریال 8000
												</h4>
											</div>
											<button class="delete">
												<i class="fa fa-close"></i>
											</button>
										</div>
									</div>
									<div class="cart-summary">
										<small>تعداد انتخاب شده 2</small>
										<h5>کل پول : ریال 38000</h5>
									</div>
									<div class="cart-btns">
										<a href="#">View Cart</a> <a href="#">Checkout <i
											class="fa fa-arrow-circle-right"></i></a>
									</div>
								</div>
							</div>
							<!-- /Cart -->


							<!-- Menu Toogle -->
							<div class="menu-toggle">
								<a href="#"> <i class="fa fa-bars"></i> <span>Menu</span>
								</a>
							</div>
							<!-- /Menu Toogle -->
						</div>
					</div>
					<!-- /ACCOUNT -->
				</div>
				<!-- row -->
			</div>
			<!-- container -->
		</div>
		<!-- /MAIN HEADER -->
	</header>
	<!-- /HEADER -->

	<!-- NAVIGATION -->
	<nav id="navigation">
		<!-- container -->
		<div class="container">
			<!-- responsive-nav -->
			<div id="responsive-nav">
				<!-- NAV -->
				<ul class="main-nav nav navbar-nav">
					<li class="active"><a href="#">صفحه اصلی</a></li>
					<li><a href="signin">signin</a></li>
					<li><a href="show_all_products">signup</a></li>
					<li><a href="indexAdmin">Admin</a></li>


				</ul>
				<!-- /NAV -->
			</div>
			<!-- /responsive-nav -->
		</div>
		<!-- /container -->
	</nav>
	<!-- /NAVIGATION -->

{% block content %}
{% endblock %}


	<!-- NEWSLETTER -->
	<div id="newsletter" class="section"></div>
	<!-- NEWSLETTER -->




	<!-- FOOTER -->
	<footer id="footer">
		<!-- top footer -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-4 col-xs-12">
						<div class="footer">
							<h3 class="footer-title">ارتباط با پروگرامر</h3>
							<p>این سایت رولد محمود شاه ساخته است</p>
							<ul class="footer-links">

								<li><a href="#"><i class="fa fa-map-marker"></i>پوهنتون کابل</a></li>
								<li><a href="#"><i class="fa fa-phone"></i>00989044861768</a></li>
								<li><a href="#"><i class="fa fa-envelope-o"></i>saeedamini506750@gmail.com</a></li>

							</ul>
						</div>
					</div>


					<div class="col-md-4 col-xs-12">
						<div class="footer">
							<h3 class="footer-title">ارتباط با ما</h3>

							<ul class="footer-links">
								<li><a href="#"><i class="fa fa-map-marker"></i> تهران</a></li>
								<li><a href="#"><i class="fa fa-phone"></i>+989036902400</a></li>
								<li><a href="#"><i class="fa fa-envelope-o"></i>
										smartcar@email.com</a></li>

							</ul>
						</div>
					</div>
					<div class="col-md-4 col-xs-12">
						<div class="footer">
							<h3 class="footer-title">ارتباط با ما</h3>

							<ul class="footer-links">
								<li><a href="#"><i class="fa fa-map-marker"></i> مشهد</a></li>
								<li><a href="#"><i class="fa fa-phone"></i>+989036902400</a></li>
								<li><a href="#"><i class="fa fa-envelope-o"></i>
										smartcar@email.com</a></li>

							</ul>
						</div>
					</div>



				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>

						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
	</footer>
	<!-- /FOOTER -->
   
   
   
    
   
    
    
	<!-- jQuery Plugins -->
	<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/slick.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/nouislider.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.zoom.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>
</html>

webapp/templates/index.html
{% extends "base.html"%}

{% block content %}

	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<div class="col-md-12">
					<div class="section-title">
						<div class="section-nav">
							<ul class="section-tab-nav tab-nav">
								<h1>
									<li class="active">محصولات پر فروش ما</li>
								</h1>

							</ul>
						</div>
					</div>
				</div>
				
				<!-- shop -->

				<div class="col-md-4 col-xs-12">
					<div class="shop">
						<div class="shop-img">
							<img src="{{ url_for('static', filename='./img/2630035505/2630035505(2).jpg ') }}" alt="">
						</div>
						<div class="shop-body">
							<h3>
								mark <br>name
							</h3>
							<a href="#" class="cta-btn">AF 35,000 <i
								class="fa fa-arrow-circle-right"></i></a>
						</div>
					</div>
				</div>
				<!-- /shop -->
				
				<!-- shop -->

				<div class="col-md-4 col-xs-12">
					<div class="shop">
						<div class="shop-img">
							<img src="{{ url_for('static', filename='./img/2630035505/2630035505(2).jpg ') }}" alt="">
						</div>
						<div class="shop-body">
							<h3>
								mark <br>name
							</h3>
							<a href="#" class="cta-btn">AF 35,000 <i
								class="fa fa-arrow-circle-right"></i></a>
						</div>
					</div>
				</div>
				<!-- /shop -->
				
				<!-- shop -->
				<div class="col-md-4 col-xs-12">
					<div class="shop">
						<div class="shop-img">
							<img src="{{ url_for('static', filename='./img/2630035505/2630035505(2).jpg ') }}" alt="">
						</div>
						<div class="shop-body">
							<h3>
								mark <br>name
							</h3>
							<a href="#" class="cta-btn">AF 35,000 <i
								class="fa fa-arrow-circle-right"></i></a>
						</div>
					</div>
				</div>
				<!-- /shop -->
				
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /SECTION -->







	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

				<!-- Company details -->
				<div class="col-md-12">
					<div class="Company-details">


						<p class="farsi">
						<h1 class="Company-name">Smart Car</h1>
						<h4>
							با خوش آمدگویی به Smart Car <br> بهترین منبع برای لوازم یدکی
							ماشین‌های هیوندایی در تهران! <br> Smart Car یک شرکت است که
							با هدف فراهم کردن بهترین لوازم یدکی ماشین‌های هیوندایی در تهران
							تأسیس شده است. ما به ارمغان می‌آوریم کیفیتی بی‌نظیر و خدماتی
							استثنایی برای مشتریان عزیزمان. <br> با ما، مطمئن باشید که هر
							قطعه یدکی که از Smart Car تهیه می‌کنید، از بهترین کیفیت و
							استانداردهای بین‌المللی برخوردار است. ما با انتخاب دقیق و اخذ
							محصولات از منابع معتبر خارجی، اطمینان حاصل می‌کنیم که ماشین شما
							همواره در بهترین حالت ممکن عمل می‌کند. به عنوان یک شرکت تازه
							‌تأسیس، Smart Car از اینکه به جمع مشتریان ما اضافه شوید، بسیار
							خوشحال خواهد شد. بازدید از وب‌سایت ما و تجربه کردن خدمات ما، به
							شما نشان خواهد داد که چرا Smart Car انتخاب مناسبی برای تأمین
							لوازم یدکی ماشین‌های هیوندایی در تهران است. <br> با تشکر از
							اعتماد شما، ما در Smart Car متعهدیم تا همیشه بهترین خدمات و
							محصولات را به شما ارائه دهیم.
						</h4>
						</p>



					</div>
				</div>



			</div>
			<!-- row -->
		</div>
		<!-- container -->
	</div>
	<!-- /SECTION -->


	<!-- NEWSLETTER -->
	<div id="newsletter" class="section"></div>
	<!-- NEWSLETTER -->

	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">

						<div class="section-nav">
							<ul class="section-tab-nav tab-nav">
								<h1>محصولات جذاب ما</h1>

							</ul>
						</div>
					</div>
				</div>
				<!-- /section title -->


				<!-- Products tab & slick -->
				<div class="col-md-12">
					<div class="row">
						<div class="products-tabs">
							<!-- tab -->
							<div id="tab1" class="tab-pane active">
								<div class="products-slick" data-nav="#slick-nav-1">
									{% for products in products %}
									<!-- product -->
									<div class="product">
										<div class="product-img">
											<img src="{{ url_for('static', filename='img/' + products['image_name']) }}" alt="">
											<div class="product-label">
												<span class="sale">-30%</span> <span class="new">NEW</span>
											</div>
										</div>
										<div class="product-body">
											<p class="product-sumsong">{{ products['product_mark'] }}</p>
											<h3 class="product-name"><a href="{{ url_for('views.show_product', product_id=products['product_ID']) }}">{{ products['product_name'] }}</a></h3>
											<p class="product-explan">{{ products['product_port'] }}</p>
											<div class="product-rating">
												<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i>
											</div>
											<div class="product-btns">
												<button class="add-to-wishlist">
													<i class="fa fa-heart-o"></i><span class="tooltipp">اضافه کردن به لیست دلخواه</span>
												</button>
												<button class="quick-view">
													<i class="fa fa-eye"></i><span class="tooltipp">نمایش محصول</span>
												</button>
											</div>
										</div>
										<div class="add-to-cart">
											<button class="add-to-cart-btn">
												<i class="fa fa-shopping-cart"></i> <a href="{{ url_for('views.show_product', product_id=products['product_ID']) }}">نمایش محصول</a>
											</button>
										</div>
									</div>
									{% endfor %}
									</div>
								<div id="slick-nav-1" class="products-slick-nav"></div>
							</div>
							<!-- /tab -->
						</div>
					</div>
				</div>
				<!-- Products tab & slick -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /SECTION -->


	<!-- NEWSLETTER -->
	<div id="newsletter" class="section"></div>
	<!-- NEWSLETTER -->

	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

				<!-- Company details -->
				<div class="col-md-12">
					<div class="Company-details">
						<h1 class="title">چرا ما را انتخاب کنید</h1>
						<p>
						<h4>
							با Smart Car، انتخابی هوشمندانه! <br> آیا به دنبال یک تجربه
							خرید بی‌نظیر برای لوازم یدکی ماشین خود هستید؟ <br> با Smart
							Car، شما از تمامی خدمات و محصولاتی که به دنبال آن‌هستید، بهره‌مند
							خواهید شد. اینجا چند دلیل برای انتخاب ما: <br> ۶ ماه
							گارانتی: ما به کیفیت محصولاتمان اعتماد داریم، بنابراین با ارائه ۶
							ماه گارانتی، اطمینان حاصل می‌کنیم که مشتریان ما از خرید خود لذت
							می‌برند و در صورت هر گونه مشکل، اعتماد خود را به ما بسپارند. <br>ارسال
							رایگان: همراه با Smart Car، ارسال رایگان به سراسر کشور شامل تمامی
							خریدهای شما است. ما به راحتی و رضایت شما اهمیت می‌دهیم و برای
							همین ارسال سریع و رایگان را فراهم کرده‌ایم.<br> پشتیبانی
							قوی: تیم ما از پشتیبانی مشتریان مجرب و متعهد تشکیل شده است که
							همیشه در دسترس هستند تا به شما در هر مرحله از فرآیند خرید کمک
							کنند و هر گونه سوال یا مشکلی را رفع کنند.<br> بازگشت محصول:
							اگر به هر دلیلی از خرید خود راضی نبودید، شما می‌توانید محصول را
							به ما بازگردانید و پول خود را دریافت کنید. رضایت شما از خرید ما
							در اولویت اول قرار دارد.<br> با Smart Car، بهترین تجربه خرید
							را تجربه کنید. ما اینجا هستیم تا شما را در هر مرحله از فرآیند
							خرید همراهی کنیم و اطمینان حاصل کنیم که خودروی شما به بهترین شکل
							ممکن عمل می‌کند.<br>
						</h4>
						</p>






					</div>
				</div>



			</div>
			<!-- row -->
		</div>
		<!-- container -->
	</div>
	<!-- /SECTION -->
	<!-- NEWSLETTER -->
	<div id="newsletter" class="section"></div>
	<!-- NEWSLETTER -->
	
	
	
	<!--start section -->
	<section id="contact">

		<h1 class="section-header">به راحتی با ما ارتباط برقرار کنید</h1>
		<div class="col-sm-12 col--12">
		
		</div>
		<div class="contact-wrapper">

			<!-- Left contact page -->

			<form id="contact-form" class="form-horizontal" role="form">

				<div class="form-group">
					<div class="col-sm-12">

						<input type="text" class="form-control" id="name"
							placeholder="نام خود را بنویسید" name="name" value="" required>
					</div>
				</div>

				<div class="form-group">
					<div class="col-sm-12">

						<input type="email" class="form-control" id="email"
							placeholder="ایمیل خود را بنویسید" name="email" value="" required>
					</div>
				</div>

				<textarea class="form-control" rows="10" placeholder="پیام خود را بنویسید"
					name="message" required></textarea>

				<button class="btn btn-primary send-button" id="submit"
					type="submit" value="SEND">
					<div class="alt-send-button">
						<i class="fa fa-paper-plane"></i><span class="send-text">SEND</span>
					</div>

				</button>

			</form>

			<!-- Left contact page -->

			<div class="direct-contact-container">

				<ul class="contact-list">
					<li class="list-item"><i class="fa fa-map-marker fa-2x"><span
							class="contact-text place">ایران, تهران</span></i></li>

					<li class="list-item"><i class="fa fa-phone fa-2x"><span
							class="contact-text phone"><a href="tel:1-212-555-5555"
								title="Give me a call">(+98) 9036902400</a></span></i></li>

					<li class="list-item"><i class="fa fa-envelope fa-2x"><span
							class="contact-text gmail"><a href="mailto:#"
								title="Send me an email">smartcar@gmail.com</a></span></i></li>

				</ul>

				<hr class="hrRed">
				<ul class="social-media-list">
					<li><a href="#" target="_blank" class="contact-icon"> <i
							class="fa fa-facebook-f" aria-hidden="true"></i></a></li>
					<li><a href="#" target="_blank" class="contact-icon"> <i
							class="fa fa-telegram" aria-hidden="true"></i></a></li>
					<li><a href="#" target="_blank" class="contact-icon"> <i
							class="fa fa-twitter" aria-hidden="true"></i></a></li>
					<li><a href="#" target="_blank" class="contact-icon"> <i
							class="fa fa-instagram" aria-hidden="true"></i></a></li>
				</ul>
				<hr class="hrRed">


			</div>

		</div>

	</section>

	<!-- section -->


	{% endblock %}